# Copyright (c) 2022 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author:  Jannis Schönleber <janniss@iis.ee.ethz.ch>

name: lint-license

on: [push, pull_request, workflow_dispatch]

jobs:
  lint-license:
    runs-on: ubuntu-latest
    steps:
    - name: lint license
      uses: pulp-platform/pulp-actions/lint-license@v2
      with:
        license: |
          Copyright \(c\) (\d{4}(-\d{4})?\s)?(ETH Zurich and University of Bologna|lowRISC contributors).
          (Solderpad Hardware License, Version 0.51|Licensed under the Apache License, Version 2.0), see LICENSE for details.
          SPDX-License-Identifier: (SHL-0.51|Apache-2.0)
        exclude_paths: |
          deps
